import os

bio    = ['ICI-AKI', 'ICI-AKI', 'ATN', 'ATN', 'ATN', 'ICI-AKI', 'ICI-AKI', 'ATN']
labels = ['case', 'case', 'control', 'control', 'control', 'case', 'case', 'control']
groups = ['20241025__200743__BWH_20241025_SHRUTI_RACHEL', '20241025__200743__BWH_20241025_SHRUTI_RACHEL',
          '20241025__200743__BWH_20241025_SHRUTI_RACHEL', '20241025__200743__BWH_20241025_SHRUTI_RACHEL',
          '20240803__182820__BWH_20240803_skin_Shruti_kidney', '20240803__182820__BWH_20240803_skin_Shruti_kidney',
          '20240803__182820__BWH_20240803_skin_Shruti_kidney', '20240803__182820__BWH_20240803_skin_Shruti_kidney']

samples1 = ['output-XETG00392__0045655__BS21-N65682A2__20241025__201009',	
            'output-XETG00392__0045655__BS22-T41795A1__20241025__201009', 
            'output-XETG00392__0045655__BS24-M35359A1__20241025__201009',
            'output-XETG00392__0045655__BS24-R31519A2__20241025__201009']
samples2 = ['output-XETG00150__0018462__BS22_12012A1__20240803__183643',
 	    'output-XETG00150__0018462__BS23_49001A1__20240803__183643',
            'output-XETG00150__0018462__BS23_52206A2__20240803__183643',
	    'output-XETG00150__0018462__BS2_61615A1__20240803__183643']

rule process_xenium_seurat:
     input:
         case = "../data/kidney/{group}/{sample}"
     output:
         h5ad = "rds/{bio}/{group}:{sample}.rds",
         fig  = "figure/{bio}/{group}:{sample}umap.pdf",
         sp   = "figure/{bio}/{group}:{sample}spatial.pdf"
     conda: "r"
     params:
         output = "{bio}/{group}:{sample}"
     shell:
         "Rscript scripts/load_view.r {input} --output {params.output} --normalize"

rule process_xenium:
     input:
         case = "../data/kidney/{group}/{sample}"
     output:
         h5ad = "h5ad/{bio}/{group}/{sample}.h5ad",
         fig = "fig/{bio}/{group}/{sample}_spatial_check.png"
     conda: "scimilarity"
     script:
         "scripts/preprocess.py"


output_h5ad = expand("h5ad/{bio}/{group}/{sample}.h5ad", zip, group=groups, sample=samples1+samples2, bio=bio)
output_rds  = expand("rds/{bio}/{group}:{sample}.rds", zip, group=groups, sample=samples1+samples2, bio=bio)
output_fig  = expand("figure/{bio}/{group}:{sample}spatial.pdf", zip, group=groups, sample=samples1+samples2, bio=bio)

rule all:
     input:
         output_h5ad, output_rds, output_fig
     default_target: True
